sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

before_install:
  - docker pull lacledeslan/gamesvr-ut2004

script:
  - docker version
  - docker build --no-cache --tag lltest/gamesvr-ut2004-freeplay --tag lacledeslan/gamesvr-ut2004-freeplay --build-arg BUILDNODE=TravisCI --build-arg SOURCE_COMMIT="$TRAVIS_COMMIT" . -f linux.Dockerfile

notifications:
  slack:
    secure: skb8/HG6BW9kkSxjcW9YV3/3nxsoRWDm8WE55qgQC9aUv5e09tK27N0l876i8oe+jVTSB5bo/C1PGVLoi0EYY68qM3Q+BPY5ykvbocGUfeYLqCI0do6QBEPWLrYrqLrNF0CqoLObLYigCQvBNwMP3WX7d/B5fpiGzgE88vii1aIsBG/fVujrpSe70dowAUkFeDaW9twIBCn3gs0b4lZMW8d1l1QbonaROz9dOampQ/0JrdBuhTdo5MXfVOWbBmJig5VLDzvqopjRd4/gJqZZ0ZlAzAFh2KEd1pO1QvDptY2PmbABA4UTHpyBVmR2+zCsQJuKblTOUBvo/58BHwD97IS9CHukBN4xxCgf5yJiGQtoz6WlBrybtyaJ23iyyn75EtLpkw3+A790BXs0mt3/YLs5zCWU8GnS0p08kiltFG+QoMK6tqACeorWozYn6Mq+x1P86eH7GLSfzbrH4pXPsTz3uQetc10UUJt8/tode8uZ3x3SfUFrot/VvRWwzK+JIszW9sn6CxqieNHpEgbaRKw1Mj8m03lfb6a1PNALaM712CQYhkBv9gQDHRnjBuF676SAUHiHbP2tbXks6qapl7VGYXktVgD2EwHhcu+7gcJPi0cx2j4JlGAy4ey6etTjXp4/NrP2J1+3VG0w5qvDBr5pzNSSho6t2YED2vkgzp0=

before_deploy:
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin;
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-ut2004-freeplay
  on:
    branch: master
after_deploy:
  - curl -X POST https://hooks.microbadger.com/images/lacledeslan/gamesvr-ut2004-freeplay/$MICROBADGER_TOKEN
